source/api/urls.py
from django.urls import include, path
from rest_framework import routers

from source.api import views

router = routers.DefaultRouter()

router.register(r'articles', views.ArticleViewSet)
router.register(r'comments', views.CommentViewSet)
router.register(r'vote', views.VoteViewSet)

app_name = 'api'


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('source.webapp.urls')),
    path('api/', include('source.api.urls')),
]

source/webapp/urls.py
from django.urls import path

from .views import ArticleListView, ArticleDetailView

urlpatterns = [
	path('', ArticleListView.as_view(), name='article'),
	path('article/<int:pk>/', ArticleDetailView.as_view(), name='article')
]

app_name = 'webapp'

source/api/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models
from django.db import IntegrityError
from django.contrib.auth.models import User


class Article(models.Model):
	author_name = models.CharField(max_length=60)
	title = models.CharField(max_length=500)
	link = models.URLField(max_length=200)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.title}"


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='commented_by')
	article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_comment')
	content = models.TextField(max_length=1500)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.content


class Vote(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='article_vote')
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_vote')

	def __str__(self):
		return str(self.article.author_name)

source/api/views.py
from rest_framework import viewsets
from source.webapp.models import Article, Comment, Vote

from source.api.serializers import ArticleSerializer, CommentSerializer, VoteSerializer


class ArticleViewSet(viewsets.ModelViewSet):
	queryset = Article.objects.all()
	serializer_class = ArticleSerializer


class CommentViewSet(viewsets.ModelViewSet):
	queryset = Comment.objects.all()
	serializer_class = CommentSerializer


class VoteViewSet(viewsets.ModelViewSet):
	queryset = Vote.objects.all()
	serializer_class = VoteSerializer

source/webapp/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from .models import Article, Comment,Vote


class ArticleListView(ListView):
	model = Article
	template_name = 'article/article_list.html'
	context_object_name = 'articles'


class ArticleDetailView(DetailView):
	model = Article
	template_name = 'article/article_detail.html'
	context_object_name = 'article'

source/webapp/templates/article/article_detail.html
{% extends 'base.html' %}
{% block container %}
<p class="lh-1">Title: {{ article.title }}</p>
<p class="lh-sm">Link: {{ article.link }}</p>
<p class="lh-base">Author {{ article.author_name }}</p>

<h6>Comments:</h6>
{% for comment in article.article_comment.all %}
<hr/>
<p class="lh-1">Test: {{ comment.user }}</p>
<p class="lh-sm">Comment: {{ comment.content }}</p>
<p class="lh-base">Commented at: {{ comment.created_at }}</p>
<hr/>
{% endfor %}

{% endblock %}

source/webapp/templates/article/article_list.html
{% extends 'base.html' %}
{% block container %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Author</th>
      <th scope="col">Title</th>
      <th scope="col">Link</th>
      <th scope="col">Comment(s)</th>
      <th scope="col">Votes</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ article.author_name }}</td>
      <td>{{ article.title }}</td>
      <td><a href="{{ article.link }}">{{ article.link }}</a></td>
      {% if article.article_comment.first %}
      <td><a href="{% url "webapp:article" article.pk %}">
      {{ article.article_comment.first }}</a> <small>(and others)</small></td>
      {% endif %}
      <td>{{ article.article_vote.count }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

source/webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>HackerNews</title>
  </head>
  <body>
    <div class='container'>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">HackerNews</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <!-- <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#"></a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Pricing</a>
        <a class="nav-link disabled">Disabled</a>
      </div> -->
    </div>
  </div>
</nav>
    </div>
    <div class="container">
      {% block container %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>